FROM golang:1.12.1-alpine AS builder

RUN apk add --update git
COPY . /go/src/k8s.io/autoscaler
RUN cd /go/src/k8s.io/autoscaler/cluster-autoscaler && CGO_ENABLED=0 go build -ldflags="-s -w" -o cluster-autoscaler

FROM alpine:latest
COPY --from=builder /go/src/k8s.io/autoscaler/cluster-autoscaler/cluster-autoscaler /bin/cluster-autoscaler
ENTRYPOINT ["/bin/cluster-autoscaler"]
